FROM python:3.8.0

RUN apt-get update && apt-get upgrade -y && apt-get install libspatialindex-dev -y && /usr/local/bin/python -m pip install --upgrade pip

WORKDIR /opt/oco2peak/
COPY requirements-dev.txt .
RUN pip install --no-cache-dir -r requirements-dev.txt

COPY docker-entrypoint.sh ./docker-entrypoint.sh
RUN chmod +x ./docker-entrypoint.sh

# Jupyter
EXPOSE 8888
# Dash
EXPOSE 8050

ENTRYPOINT [ "./docker-entrypoint.sh" ]
