version: '3.3'

services:
  oco2-dev:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    shm_size: '4gb'
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      # exposed on host : in guest
      # Dash
      - 7901:8050
      # Jupyter will be on http://localhost:7988
      - 7988:8888
    environment:
      HOME_DIR: "/opt/oco2peak/"
    volumes: 
      - type: bind
        # YOU HAVE TO CHANGE THIS
        source: /media/NAS-Divers/dev/datasets/
        target: /mnt/datasets/
      - type: bind
        source: ./
        target: /opt/oco2peak/
