# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Datasets": "oco2peak-datasets.ipynb",
         "compute_haversine_formula": "oco2peak-find_peak.ipynb",
         "compute_distance": "oco2peak-find_peak.ipynb",
         "load_data": "oco2peak-find_peak.ipynb",
         "gaussian": "oco2peak-find_peak.ipynb",
         "peak_detection": "oco2peak-find_peak.ipynb",
         "gaussian_fit_on_df": "oco2peak-find_peak.ipynb",
         "gaussian_fit_on_file": "oco2peak-find_peak.ipynb",
         "build_sounding_scatter": "oco2peak-map.ipynb",
         "build_sounding_map": "oco2peak-map.ipynb",
         "build_world_map": "oco2peak-map.ipynb",
         "get_file_list": "oco2peak-nc4_convert.ipynb",
         "get_nc4_raw_content": "oco2peak-nc4_convert.ipynb",
         "get_np_table": "oco2peak-nc4_convert.ipynb",
         "columns": "oco2peak-nc4_convert.ipynb",
         "get_dataframe": "oco2peak-nc4_convert.ipynb",
         "get_pattern_yearmonth": "oco2peak-nc4_convert.ipynb",
         "process_files": "oco2peak-nc4_convert.ipynb",
         "estimate_emission": "oco2peak_find_source.ipynb",
         "plot_emission": "oco2peak_find_source.ipynb"}

modules = ["datasets.py",
           "find_peak.py",
           "oco2map.py",
           "nc4_convert.py",
           "find_source.py"]

doc_url = "https://trancept.github.io/oco2peak/"

git_url = "https://github.com/trancept/oco2peak/tree/master/"

def custom_doc_links(name): return None
