# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Datasets": "oco2peak-datasets.ipynb",
         "gaussian": "oco2peak-find_peak.ipynb",
         "build_sounding_scatter": "oco2peak-map.ipynb",
         "build_sounding_map": "oco2peak-map.ipynb",
         "build_world_map": "oco2peak-map.ipynb"}

modules = ["datasets.py",
           "find_peak.py",
           "oco2map.py"]

doc_url = "https://trancept.github.io/oco2peak/"

git_url = "https://github.com/trancept/oco2peak/tree/master/"

def custom_doc_links(name): return None
